### ISSUE TITLE
Asserts triggers `TS2531 [ERROR]: Object is possibly 'null'` on nightly

### ISSUE THREAD

**Issue by jajaperson** [denoland/deno_std#2556]
**Describe the bug**
When importing from `testing/asserts.ts` on nightly Deno, I get a TS generated error regarding [this line](https://github.com/denoland/deno_std/blob/main/testing/asserts.ts#L359) in the body of a function I'm not using. Looking at the code, I can't see how typescript thinks the object is possibly null.

```
error: TS2531 [ERROR]: Object is possibly 'null'.
      actualTypeStr = actual.constructor?.name ?? "Object";
                      ~~~~~~
    at https://deno.land/std@0.152.0/testing/asserts.ts:359:23
```

![Screen Shot 2022-08-24 at 4 19 19 pm](https://user-images.githubusercontent.com/25611007/186367741-94cfaa42-509d-4715-ad6a-e349f5d562da.png)

[Here is the GitHub action in question](https://github.com/jajaperson/copb/runs/7990196972?check_suite_focus=true)

**Steps to Reproduce**

Using [this GitHub actions script](https://github.com/jajaperson/copb/blob/main/.github/workflows/deno.yaml), using nightly Deno. The test suite only imports `{ assertEquals }`.

```yaml

name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [v1.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Check formatting
        run: deno fmt --check **/*.ts
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno: [v1.x, nightly]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Run unit tests on Deno
        run: deno test
      - uses: actions/setup-node@v2
      - name: Build and run unit tests on the npm version
        run: deno run -A ./scripts/build_npm.ts
```
